### PR TITLE
seperate projects and build individual nuget packages;

### PR DESCRIPTION
**Pull request by NtFreX**
Hey I've seperated the transports into different projects. I also updated the projects to use the newest csproj format. This is only compatible with msbuild 15.

I've removed the .nuspec file as the new msbuild version includes nuget. The packages can now be configured in the csproj file.

It would be nice if you could take a look and let me know if this is what you expected.

For issue https://github.com/Inside-Sistemas/mailer.net/issues/4.

### CODE REVIEW

**Comment by lira92** [comment]
@NtFreX nice, thanks for your contributing, this is exactly what I expected. I will execute locally as soon as possible and if everything is ok, I will merge this PR.

**Comment by lira92** [comment]
@NtFreX Can you resolve conflicts and if is possible, squash your commits? i merged a PR with async send method.

**Comment by NtFreX** [comment]
I've merged the master branch. I'm not quite sure how I can squash my commits. Maybe I need to create a new branch?

**Comment by lira92** [comment]
@NtFreX no, let me help you, I you dont't have the upstream origin added, execute:
git remote add upstream https://github.com/Inside-Sistemas/mailer.net.git
After this in yout branch, execute:
git rebase -i upstream/master and change 'pick' to 's' in all commits except first. I believe this will work.

**Comment by NtFreX** [comment]
```
C:\Projects\mailer.net>git remote add upstream https://github.com/Inside-Sistemas/mailer.net.git

C:\Projects\mailer.net>git rebase -i upstream/master
fatal: Needed a single revision
invalid upstream upstream/master
```

**Comment by lira92** [comment]
@NtFreX I believe that it happened because you didn't create a new branch, I will merge anyway. Thanks for your contributing, you did a great job.

**Pull request merged**
